# Generated by Django 4.2.2 on 2023-06-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_chargeworkload_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclient',
            name='workload',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
