# Generated by Django 4.2.2 on 2023-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_externalclient_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='address_exact',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='is_feasibility_electrical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='well',
            name='latitude',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='link_location',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='longitude',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='pickup_type',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
