# Generated by Django 4.2.2 on 2023-06-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_well_address_exact_well_is_feasibility_electrical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('photo', models.FileField(upload_to='liftings/wells/photos')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.well')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
