# Generated by Django 4.2.2 on 2023-06-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_photowell'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('dga_resolution', models.CharField(blank=True, max_length=1200, null=True)),
                ('shac', models.CharField(blank=True, max_length=1200, null=True)),
                ('daily_publication_date', models.DateField(blank=True, null=True)),
                ('term_installation_measurement', models.DateField(blank=True, null=True)),
                ('initial_transmission_term', models.DateField(blank=True, null=True)),
                ('dga_standard', models.CharField(blank=True, max_length=1200, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.well')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
