# Generated by Django 4.2.2 on 2023-06-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_rename_note_valueelement_value_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteproject',
            name='for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_user_note_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteproject',
            name='is_note',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noteproject',
            name='is_task',
            field=models.BooleanField(default=True),
        ),
    ]
