# Generated by Django 4.2.5 on 2023-10-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_usercatchmentpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifting',
            name='person_in_charge_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.employee'),
        ),
    ]
